@url = csp-ws2023.northeurope.azurecontainer.io
@port = 8080
@protocol = http
@fqdn = {{protocol}}://{{url}}:{{port}}

###
GET {{fqdn}}/Users
Accept: application/json

###
@getId = 2e1ef15a-0ba0-4a62-9da7-55f30f7c41a6
GET {{fqdn}}/Users/{{getId}}
Accept: application/json

###
POST {{fqdn}}/Users
Content-Type: application/json

{
    "Id": "{{$guid}}",
    "Name": "John Doe",
    "Email": "John@fake.com"
}

###
@deleteId = 2e1ef15a-0ba0-4a62-9da7-55f30f7c41a6
DELETE {{fqdn}}/Users/{{deleteId}}
